repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
        args: [--safe, -S]

-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy

-   repo: local
    hooks:
    -   id: unittest
        name: unittest
        entry: python -m unittest discover
        language: python
        'types': [python]
        args: ["-p '*test.py'"] # Probably this option is absolutely not needed.
        pass_filenames: false
        stages: [commit]
